database:
  driver: mysql
  connection: root:root@tcp(localhost:3306)/hublabs_sale_record?charset=utf8&parseTime=True&loc=UTC
orderEvent:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: hublabs-order
eventBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: hublabs-sale-record
errorEventBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: sale-process-fail
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
debug: true
services:
  productApi:
  membershipAddr:
  membershipBenefitAddr:
  couponAddr:
  placeManagementAddr:
  payamtApi:
serviceName: sale-record-api
